name: PR

on:
  pull_request:
    paths-ignore:
      - "**/README.md"
      - "assets/**"

defaults:
  run:
    shell: bash
    working-directory: zeapp

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: "Setup Java 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Assemble Debug"
        run: ./gradlew :android:assembleDebug --no-daemon
      - name: "Upload Debug APK to GitHub"
        uses: actions/upload-artifact@v3
        with:
          name: Debug APK
          path: zeapp/android/build/outputs/apk/debug/android-debug.apk

  format:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: "Setup Java 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Lint"
        run: ./gradlew ktlintFormat --no-daemon

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: "Setup Java 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Lint"
        run: ./gradlew lint --no-daemon
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: "Setup Java 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Detekt"
        run: ./gradlew detekt
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: "Setup Java 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Test"
        run: ./gradlew linuxTest
    
